struct APEvents {
    static let bannerClick = "appobanner.click"
    static let bannerLoadFail = "appodeal.banner.load_fail"
    static let bannerLoad = "appodeal.banner.load"
    static let bannerShow = "appodeal.banner.show"
    static let interstitialClick = "appodeal.interstitial.click"
    static let interstitialShow = "appodeal.interstitial.show"
    static let interstitialClose = "appodeal.interstitial.close"
    static let interstitialShowFailed = "appodeal.interstitial.show_fail"
    static let interstitialLoad = "appodeal.interstitial.load"
    static let interstitialLoadFail = "appodeal.interstitial.load_fail"
    static let interstitialWillClose = "appodeal.interstitial.will_close"
    static let ready = "appodeal.ready"
    static let rewardVideoClick = "appodeal.reward_video.click"
    static let rewardVideoComplete = "appodeal.reward_video.complete"
    static let rewardVideoShowFailed = "appodeal.reward_video.show_fail"
    static let rewardVideoShow = "appodeal.reward_video.show"
    static let rewardVideoLoad = "appodeal.reward_video.load"
    static let rewardVideoClose = "appodeal.reward_video.close"
    static let rewardVideoLoadFail = "appodeal.reward_video.load_fail"
    static let nativeClick = "appodeal.native.click"
    static let nativeShow = "appodeal.native.show"
    static let nativeLoadFail = "appodeal.native.load_fail"
    static let nativeLoad = "appodeal.native.load"
}
